---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------


### Chart A
### Introduction
Dear reader,

For this project, I am interested in comparing Marlon Hoffstadt his music with trance music from the 90’s. Marlon Hoffstadt, also know als DJ Daddy Trance, is a German DJ who combines the genres techno, house, trance and Eurodance. Personally, I am a huga fan of Marlon Hoffstadt his music. It is very creative and I really like the fact that he gets his inspiration from 90s trance music. I am wondering what features, think about dancealbility, tempo and key for example have changed since the 90s.


*
test 2

### First visualisation
test 3
 #histogram of marlontrance and ninetiestrance together in one plot
playlist |>
  ggplot(aes(x = energy)) +
  geom_histogram(binwidth = 0.1) +
  facet_wrap(~category) + ggtitle("histogram of marlontrance and ninetiestrance")


*
test 4

### Conclusion and discussion
test 5


* 
test 6

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

